### ISSUE TITLE
Calculate FF descriptor for small molecule?

### ISSUE THREAD

**Issue by arifin-chemist89** [RadonPy/RadonPy#10]
In the present implementation, is it possible to calculate FF descriptor for small molecules (without connection atoms)? If not, will it be expanded to do so?

**Comment by yhayashi1986** [comment]
FF descriptor for small molecules can be calculated by FF_descriptor.ffkm_mp with `cyclic=0` option.

**Comment by arifin-chemist89** [comment]
Thank you very much for your kind response. I confirmed it works and will close this issue.
