### ISSUE TITLE
About the parameters in sample_script

### ISSUE THREAD

**Issue by lichman0405** [RadonPy/RadonPy#11]
Hi there!
I am trying to understand the code of sample_script repo.
However, I find it out that the `data` dictionary has a piece of code `os.environ.get('RadonPy_DBID')`.

Should I have a database preparation before I start the code?
Otherwise, it may report 
`    smi_list = data['smiles_list'].split(',')
AttributeError: 'NoneType' object has no attribute 'split'`

Hope you may drop me a line.

**Comment by yhayashi1986** [comment]
Just input an arbitrary string for RadonPy_DBID.
The string entered in RadonPy_DBID will be used as the name of the automatically created working directory. The log files of molecular dynamics and DFT calculations are output in this working directory.

RadonPy_SMILES must be entered with the SMILES string of the polymer you want to calculate.

The sample scripts should be run in the following order: qm.py, eq.py, rst_eq.py, and tc.py.

**Comment by lichman0405** [comment]
Thanks!
Next issue here:
Do you have an experience of deploy RadonPY on Supercomputer platform with slurm jobs regulators?
I may have problems with lammps mpi slots.
I double check the `cpu_counts()` number and I am sure that I have 128 slots computing resources but the eq.py sort of showed me mpi out of slots.

I am not sure if it is VMs issues.

**Comment by yhayashi1986** [comment]
I don't know the details of slurm job management system.
Sorry.

**Comment by fly-man-fly** [comment]
> Thanks! Next issue here: Do you have an experience of deploy RadonPY on Supercomputer platform with slurm jobs regulators? I may have problems with lammps mpi slots. I double check the `cpu_counts()` number and I am sure that I have 128 slots computing resources but the eq.py sort of showed me mpi out of slots.
> 
> I am not sure if it is VMs issues.

Hello, I'm also encountering this error. Could we have a detailed chat about it?
