### ISSUE TITLE
Usage of package OPENMP

### ISSUE THREAD

**Issue by shoehangxh** [RadonPy/RadonPy#26]
Hello
Thanks for your repo! it 's a really useful tool for us who don't understand simulation very much
But i came across a situation when trying the tutorial as 

''RadonPy warning: OPENMP package is not available. Parallel number of OPENMP is changed to zero.''

I have tired command 

'conda install -c conda-forge openmpi '

but it doesn't work, it seemd like i still fail to install some of the necessary packages, so how can i solve this problem?
Looking forward for your reply! Thanks!

**Comment by yhayashi1986** [comment]
This warning message means that OpenMP package is not installed in your LAMMPS binary. The LAMMPS binary installed via conda does not include the OpenMP package. If you want to use OpenMP in LAMMPS, it is necessary that you compile the LAMMPS including the OpenMP package.

Since MPI parallelism can be used in the LAMMPS binary installed via conda, parallel computation is possible even if this message is ignored.

**Comment by shoehangxh** [comment]
Thank you for your reply!

Does it mean that parallel computation is possible when i installed LAMMPS and openMPI through conda? So that I don't need to re-install LAMMPS and OpenMP

Thanks!

**Comment by yhayashi1986** [comment]
> Does it mean that parallel computation is possible when i installed LAMMPS and openMPI through conda?
Yes, that's correct.

**Comment by shoehangxh** [comment]
Thank you very much！

**Comment by bio-punk** [comment]
I don't know how to build lammps with OpenMP.
For example, I build lammps with command
```    
    -D Kokkos_ENABLE_OPENMP=yes \
    -D BUILD_OMP=yes \
```
after I built lmp , use `lmp -h` , It shows
```
OS: Linux "Ubuntu 22.04.5 LTS" 5.15.0-119-generic x86_64

Compiler: GNU C++ 11.4.0 with OpenMP 4.5
C++ standard: C++17
Embedded fmt library version: 10.2.0
Embedded JSON class version: 3.12.0

MPI v3.1: Open MPI v5.0.8, package: Open MPI conda@69bcf91866a2 Distribution, ident: 5.0.8, repo rev: v5.0.8, May 30, 2025

Accelerator configuration:

GPU package API: CUDA
GPU package precision: mixed
KOKKOS package API: CUDA OpenMP
KOKKOS package precision: double
Kokkos library version: 4.6.2
```
but when I run radonPy, still shows
```
Starting QM calculations for  1 molecules with GPU acceleration
RadonPy info: GPU package is available.
RadonPy info: Start optimization of 2 conformers by MM level.
RadonPy warning: OPENMP package is not available. Parallel number of OPENMP is changed to zero.

```
I think this is a bug in file `radonpy/sim/lammps.py`. so I change code line 234 and line 258 to `if 'OPENMP' in l or 'USER-OMP' in l.upper():`
