### ISSUE TITLE
KeyError: 'AtomicCharge' when running equilibrium md functions

### ISSUE THREAD

**Issue by mikeboyle321** [RadonPy/RadonPy#49]
Hello,

Thank you for writing this package. It's a very exciting tool! 

I have a question about forcefield assignment at the polymer level.

I'm running the following test on polystyrene now following the tutorial pdf:

from radonpy.core import poly, utils
from radonpy.sim import qm
from radonpy.ff.gaff2_mod import GAFF2_mod
from radonpy.sim.preset import eq
import os

cpus = utils.cpu_count()

ps_smiles = '*CC(*)c1ccccc1'
mol = utils.mol_from_smiles(ps_smiles)

work_dir = 'path/to/work/dir'

ff = GAFF2_mod()
mol, energy = qm.conformation_search(mol,
                                     ff=ff,
                                     work_dir = work_dir
                                     )

qm.assign_charges(mol,
                  charge='RESP',
                  work_dir=work_dir
                  )

repeat_units = 10
atom_nubmer = monomer_atom_num*repeat_units
print(atom_nubmer)

atom_number = 1000
ter = utils.mol_from_smiles('*C')
n = poly.calc_n_from_num_atoms(mol, 
                               atom_number ,
                               terminal1=ter
                               )
homopoly = poly.polymerize_rw(mol, 
                                n,
                                tacticity='atactic'
                                )
homopoly = poly.terminate_rw(homopoly, 
                               ter)

result = ff.ff_assign(homopoly)

**It seems that the forcefield is assigned at the conformation search level. Is there a reason it needs to be reassigned after polymerization? Is there a way to pass the forcefield information from the qm calculations to the polymerize function? More importantly, the partial charges from the charge calculation are not transferred from the monomers to the polymer. This leads to the following key error when you try to run the md equilibration.**

n_chains = 10
ac = poly.amorphous_cell(homopoly,
                         n_chains
                         )

temp = 300 # K
press = 1.0 # bar 
eqmd = eq.EQ21step(ac,
                   work_dir = work_dir)
ac = eqmd.exec(temp = temp,
               press = press,
               omp = 1,
               gpu = 2,
               mpi = utils.cpu_count())

KeyError                                  Traceback (most recent call last)
Cell In[16], line 5
      2 press = 1.0 # bar 
      3 eqmd = eq.EQ21step(ac,
      4                    work_dir = work_dir)
----> 5 ac = eqmd.exec(temp = temp,
      6                press = press,
      7                omp = 1,
      8                gpu = 2,
      9                mpi = utils.cpu_count())

**File anaconda3/envs/radonpy_py311/lib/python3.11/site-packages/radonpy/sim/preset/eq.py:351, in EQ21step.exec(self, confId, f_density, max_temp, temp, press, max_press, step_list, press_ratio, time_step, eq_step, omp, mpi, gpu, intel, opt, **kwargs)
    349 utils.MolToPDBFile(self.mol, os.path.join(self.work_dir, self.pdb_file))
    350 lmp = lammps.LAMMPS(work_dir=self.work_dir, solver_path=self.solver_path)
--> 351 lmp.make_dat(self.mol, file_name=self.dat_file1, confId=confId)
    353 dt1 = datetime.datetime.now()
    354 utils.radon_print('Packing simulation (eq1) by LAMMPS is running...', level=1)

File anaconda3/envs/radonpy_py311/lib/python3.11/site-packages/radonpy/sim/lammps.py:333, in LAMMPS.make_dat(self, mol, confId, file_name, dir_name, velocity, temp, drude)
    331 dir_name = dir_name if dir_name is not None else self.work_dir
    332 dat_file = os.path.join(dir_name, file_name)
--> 333 MolToLAMMPSdata(mol, dat_file, confId=confId, velocity=velocity, temp=temp, drude=drude)
    335 return dat_file
...
   2755             coord[i][0], coord[i][1], coord[i][2]))
   2757 if velocity:
   2758     lines.append('')

KeyError: 'AtomicCharge'**

The work around to this is to recalculate the charge after polymerization by running result = ff.ff_assign(homopoly, charge='RESP'), but redoing the qm calculations of partial charges at the polymer level becomes prohibitively expensive as the number of monomers increases. **Is there a way to pass the ff and partial charges from the monomer to the polymer mol structure so that these calculations do not have to be redone?**

Thanks!
Mike Boyle

**Comment by yhayashi1986** [comment]
> It seems that the forcefield is assigned at the conformation search level. Is there a reason it needs to be reassigned after polymerization? Is there a way to pass the forcefield information from the qm calculations to the polymerize function? 

RadonPy performs MM-level pre-optimization in the conformational search for repeated units. Therefore, force fields are assigned at the conformational search level. The assigned parameters of the force field do not take into account fragments of connection points between repeating units. Therefore, reassignment is required after polymerization.

> More importantly, the partial charges from the charge calculation are not transferred from the monomers to the polymer. This leads to the following key error when you try to run the md equilibration.

The partial charges are transferred from the monomers to the polymer. The qm.assign_charges did not perform for the terminal unit in your code. Therefore, KeyError: 'AtomicCharge' has occurred.

**Comment by mikeboyle321** [comment]
Thank you for the reply! 

Is there a way to generate the partial charges for the terminal groups so that it can be passed to the polymer?

**Comment by yhayashi1986** [comment]
Please insert the following code:
`qm.assign_charges(ter, charge='RESP', work_dir=work_dir)`
after the `ter = utils.mol_from_smiles('*C')`

**Comment by mikeboyle321** [comment]
Thank you for the help!

**Comment by mikeboyle321** [comment]
Thank you for the help!
